language: ruby
services:
  - postgresql
addons:
  postgresql: '9.6'
script:
  - mkdir -p tmp/{cache,sessions}
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake spec
rvm:
  - "2.3.4"
env:
  - RAILS_ENV=test TRAVIS_BUILD=true
notifications:
  email: false
