version: '3.5'

volumes:
  pg_db:

services:
  civicDB:
    image: postgres:11-alpine
    volumes:
    - pg_db:/var/lib/postgresql/data
    - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    restart: always
    shm_size: '4gb'
    environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - PGUSER=${POSTGRES_USER}
    - PGPASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10

  civic-server:
    build: .
    image: nexus-civic-server
    #volumes:
    environment:
    - DATABASE_HOST=civicDB
    - DATABASE_USERNAME=${POSTGRES_USER}
    - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    - PGHOST=civicDB
    - PGUSER=${POSTGRES_USER}
    - PGPASSWORD=${POSTGRES_PASSWORD}
    - DB_TIMEOUT_SECS=60000
    - RAILS_WORKERS=4
    - RAILS_MIN_THREADS=8
    - RAILS_MAX_THREADS=32
    ports:
    - "3000:3000"
    command: puma -b tcp://0.0.0.0:3000
    depends_on:
    - civicDB
