default: &default
  adapter: postgresql
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: <%= ENV["DB_TIMEOUT_SECS"] || 5000 %>
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: civic_development

test:
  <<: *default
  database: civic_test
  <% if ENV['TRAVIS_BUILD'] %>
  username: postgres
  <% end %>

production:
  <<: *default
  database: civic
